### ISSUE TITLE
Remove typo's

### ISSUE THREAD

**Issue by proliteweb** [cri2net/sms-fly#1]
Hello. I try to use your package, but i receive error when try submit sms, using default Alphaname.
1) Line 24  public $alfaname 	= '**InfoCentr**'; - must me **InfoCenter**
2) Line 148  **livetime**="24"  - must be **lifetime**
Thanks.

**Comment by cri2net** [comment]
InfoCenter - changed for new users, thanks, see https://packagist.org/packages/cri2net/sms-fly#1.0.6
If you use the default alfaname, it may be more profitable for you to write $sms_fly->alfaname = false; to send SMS without the alfaname, it is cheaper.
